services:
  postgres:
    image: "postgres:17"
    volumes:
      - "${DATA_DIR:?specify data dir in .env file}/postgres:/var/lib/postgresql/data:rw"
    restart: always
    healthcheck:
      test: pg_isready -h localhost -U postgres
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 1h
      start_interval: 3s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      POSTGRES_DB: labels
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?specify password in .env file}"
    command: [
      "-c", "max_connections=1000",
      ]
    stop_grace_period: 24h
  labeler:
    build: .
    restart: always
    image: bsky.watch/labeler
    volumes:
      - "${DATA_DIR:?Specify DATA_DIR in .env file}:/data:rw"
      - "${CONFIG_FILE:-./config.yaml}:/config.yaml:ro"
    ports:
      - "${LISTEN_ADDR:-0.0.0.0:8080}:8080"
    command: [
      "--config=/config.yaml",
      "--log-level=0",
      "--listen-addr=:8080",
    ]
    depends_on:
      postgres:
        condition: service_healthy
